-- SPXAgent Supabase setup
-- Run this single file in the Supabase SQL Editor.
-- Safe to re-run on fresh or existing projects.

-- ---------------------------------------------------------------------------
-- Calls
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS call_logs (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    phone_number       text,
    caller_name        text,
    duration_seconds   integer,
    transcript         text,
    summary            text,
    recording_url      text,
    sentiment          text,
    estimated_cost_usd numeric(10,5),
    call_date          date,
    call_hour          integer,
    call_day_of_week   text,
    was_booked         boolean DEFAULT false,
    interrupt_count    integer DEFAULT 0,
    audio_codec        text,
    call_room_id       text
);

ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS caller_name text;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS sentiment text;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS estimated_cost_usd numeric(10,5);
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_date date;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_hour integer;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_day_of_week text;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS was_booked boolean DEFAULT false;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS interrupt_count integer DEFAULT 0;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS audio_codec text;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS call_room_id text;

CREATE INDEX IF NOT EXISTS idx_call_logs_phone_number
    ON call_logs (phone_number);

CREATE INDEX IF NOT EXISTS idx_call_logs_call_room_id
    ON call_logs (call_room_id);

ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all actions for service role" ON call_logs;
DROP POLICY IF EXISTS "Allow call logs all" ON call_logs;
CREATE POLICY "Allow call logs all"
    ON call_logs FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE TABLE IF NOT EXISTS call_transcripts (
    id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    call_room_id text NOT NULL,
    phone        text,
    role         text CHECK (role IN ('user', 'assistant')),
    content      text,
    created_at   timestamptz DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_call_transcripts_room
    ON call_transcripts (call_room_id);

CREATE INDEX IF NOT EXISTS idx_call_transcripts_phone
    ON call_transcripts (phone);

ALTER TABLE call_transcripts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon insert transcripts" ON call_transcripts;
DROP POLICY IF EXISTS "Allow anon select transcripts" ON call_transcripts;
DROP POLICY IF EXISTS "Allow call transcripts all" ON call_transcripts;
CREATE POLICY "Allow call transcripts all"
    ON call_transcripts FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE TABLE IF NOT EXISTS active_calls (
    room_id      text PRIMARY KEY,
    phone        text,
    caller_name  text,
    status       text DEFAULT 'ringing',
    started_at   timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    last_updated timestamptz DEFAULT timezone('utc', now()) NOT NULL
);

ALTER TABLE active_calls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon all active_calls" ON active_calls;
DROP POLICY IF EXISTS "Allow active calls all" ON active_calls;
CREATE POLICY "Allow active calls all"
    ON active_calls FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE TABLE IF NOT EXISTS call_turn_metrics (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    call_room_id       text,
    phone_number       text,
    turn_index         integer NOT NULL DEFAULT 0,
    speaker            text NOT NULL DEFAULT 'assistant',
    stt_endpoint_ms    numeric,
    kb_ms              numeric,
    llm_first_token_ms numeric,
    tts_first_audio_ms numeric,
    tool_ms            numeric,
    total_turn_ms      numeric,
    kb_used            boolean DEFAULT false NOT NULL,
    kb_skipped_reason  text,
    metadata           jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT call_turn_metrics_speaker_check CHECK (speaker IN ('assistant', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_call_turn_metrics_room_turn
    ON call_turn_metrics (call_room_id, turn_index);

CREATE INDEX IF NOT EXISTS idx_call_turn_metrics_phone_created
    ON call_turn_metrics (phone_number, created_at);

ALTER TABLE call_turn_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow call turn metrics all" ON call_turn_metrics;
CREATE POLICY "Allow call turn metrics all"
    ON call_turn_metrics FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


-- ---------------------------------------------------------------------------
-- Appointments
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS appointments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    title           text NOT NULL DEFAULT 'Appointment',
    contact_name    text,
    contact_phone   text,
    scheduled_start timestamptz NOT NULL,
    scheduled_end   timestamptz NOT NULL,
    timezone        text NOT NULL DEFAULT 'Asia/Kolkata',
    status          text NOT NULL DEFAULT 'scheduled',
    notes           text,
    source          text NOT NULL DEFAULT 'manual_ui',
    CONSTRAINT appointments_valid_status CHECK (status IN ('scheduled', 'cancelled', 'completed')),
    CONSTRAINT appointments_valid_source CHECK (source IN ('voice_agent', 'manual_ui', 'backend_api')),
    CONSTRAINT appointments_valid_window CHECK (scheduled_end > scheduled_start)
);

ALTER TABLE appointments ALTER COLUMN title SET DEFAULT 'Appointment';

DROP TRIGGER IF EXISTS set_appointments_updated_at ON appointments;
CREATE TRIGGER set_appointments_updated_at
BEFORE UPDATE ON appointments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE appointments
    DROP CONSTRAINT IF EXISTS appointments_no_overlap;

ALTER TABLE appointments
    ADD CONSTRAINT appointments_no_overlap
    EXCLUDE USING gist (
        tstzrange(scheduled_start, scheduled_end, '[)') WITH &&
    )
    WHERE (status = 'scheduled');

CREATE INDEX IF NOT EXISTS idx_appointments_scheduled_start
    ON appointments (scheduled_start);

CREATE INDEX IF NOT EXISTS idx_appointments_status
    ON appointments (status);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow internal appointment select" ON appointments;
DROP POLICY IF EXISTS "Allow internal appointment insert" ON appointments;
DROP POLICY IF EXISTS "Allow internal appointment update" ON appointments;
DROP POLICY IF EXISTS "Allow internal appointment delete" ON appointments;
DROP POLICY IF EXISTS "Allow appointments all" ON appointments;
CREATE POLICY "Allow appointments all"
    ON appointments FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


-- ---------------------------------------------------------------------------
-- Knowledge base
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS kb_sources (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_type    text NOT NULL,
    title          text NOT NULL DEFAULT '',
    source_url     text,
    raw_text       text,
    storage_bucket text,
    storage_path   text,
    mime_type      text,
    checksum       text,
    status         text NOT NULL DEFAULT 'pending',
    enabled        boolean NOT NULL DEFAULT true,
    last_synced_at timestamptz,
    sync_error     text,
    metadata       jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE kb_sources DROP CONSTRAINT IF EXISTS kb_sources_type_check;
DELETE FROM kb_sources
WHERE source_type NOT IN ('pdf_upload', 'web_url');
ALTER TABLE kb_sources
    ADD CONSTRAINT kb_sources_type_check CHECK (source_type IN ('pdf_upload', 'web_url'));

ALTER TABLE kb_sources DROP CONSTRAINT IF EXISTS kb_sources_status_check;
UPDATE kb_sources
SET status = 'error'
WHERE status NOT IN ('pending', 'ready', 'syncing', 'error', 'disabled');
ALTER TABLE kb_sources
    ADD CONSTRAINT kb_sources_status_check CHECK (status IN ('pending', 'ready', 'syncing', 'error', 'disabled'));

CREATE INDEX IF NOT EXISTS idx_kb_sources_type_status
    ON kb_sources (source_type, status);

DROP TRIGGER IF EXISTS set_kb_sources_updated_at ON kb_sources;
CREATE TRIGGER set_kb_sources_updated_at
BEFORE UPDATE ON kb_sources
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE kb_sources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow kb sources all" ON kb_sources;
CREATE POLICY "Allow kb sources all"
    ON kb_sources FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE TABLE IF NOT EXISTS kb_documents (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at     timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_id      bigint NOT NULL REFERENCES kb_sources(id) ON DELETE CASCADE,
    external_id    text NOT NULL,
    document_type  text NOT NULL DEFAULT 'generic',
    title          text NOT NULL DEFAULT '',
    body_text      text NOT NULL DEFAULT '',
    checksum       text,
    metadata       jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_documents_source_external
    ON kb_documents (source_id, external_id);

CREATE INDEX IF NOT EXISTS idx_kb_documents_source
    ON kb_documents (source_id);

DROP TRIGGER IF EXISTS set_kb_documents_updated_at ON kb_documents;
CREATE TRIGGER set_kb_documents_updated_at
BEFORE UPDATE ON kb_documents
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE kb_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow kb documents all" ON kb_documents;
CREATE POLICY "Allow kb documents all"
    ON kb_documents FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE TABLE IF NOT EXISTS kb_chunks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_id   bigint NOT NULL REFERENCES kb_sources(id) ON DELETE CASCADE,
    document_id bigint NOT NULL REFERENCES kb_documents(id) ON DELETE CASCADE,
    chunk_index integer NOT NULL,
    title       text NOT NULL DEFAULT '',
    content     text NOT NULL DEFAULT '',
    checksum    text,
    token_count integer NOT NULL DEFAULT 0,
    embedding   jsonb NOT NULL DEFAULT '[]'::jsonb,
    metadata    jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kb_chunks_document_index
    ON kb_chunks (document_id, chunk_index);

CREATE INDEX IF NOT EXISTS idx_kb_chunks_source
    ON kb_chunks (source_id);

ALTER TABLE kb_chunks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow kb chunks all" ON kb_chunks;
CREATE POLICY "Allow kb chunks all"
    ON kb_chunks FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


CREATE TABLE IF NOT EXISTS kb_ingest_jobs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    source_id   bigint REFERENCES kb_sources(id) ON DELETE CASCADE,
    source_type text NOT NULL DEFAULT 'generic',
    job_type    text NOT NULL DEFAULT 'ingest',
    status      text NOT NULL DEFAULT 'pending',
    payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_text  text,
    started_at  timestamptz,
    finished_at timestamptz,
    attempts    integer NOT NULL DEFAULT 0,
    last_result jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT kb_ingest_jobs_status_check CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled'))
);

DELETE FROM kb_ingest_jobs
WHERE source_type NOT IN ('pdf_upload', 'web_url');

CREATE INDEX IF NOT EXISTS idx_kb_ingest_jobs_status_created
    ON kb_ingest_jobs (status, created_at);

CREATE INDEX IF NOT EXISTS idx_kb_ingest_jobs_source
    ON kb_ingest_jobs (source_id);

DROP TRIGGER IF EXISTS set_kb_ingest_jobs_updated_at ON kb_ingest_jobs;
CREATE TRIGGER set_kb_ingest_jobs_updated_at
BEFORE UPDATE ON kb_ingest_jobs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE kb_ingest_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow kb ingest jobs all" ON kb_ingest_jobs;
CREATE POLICY "Allow kb ingest jobs all"
    ON kb_ingest_jobs FOR ALL TO anon, authenticated
    USING (true)
    WITH CHECK (true);


-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------

-- Call recordings are private: the API checks the caller's workspace and hands out one-minute signed links.
INSERT INTO storage.buckets (id, name, public)
VALUES ('call-recordings', 'call-recordings', false)
ON CONFLICT (id) DO UPDATE SET public = false;

DROP POLICY IF EXISTS "Public read recordings" ON storage.objects;

-- Uploads use the service role / S3 keys, which bypass row-level security; no policy opens the bucket to others.
DROP POLICY IF EXISTS "Service role write recordings" ON storage.objects;
DROP POLICY IF EXISTS "Allow recordings upload" ON storage.objects;


INSERT INTO storage.buckets (id, name, public)
VALUES ('kb-files', 'kb-files', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public read kb files" ON storage.objects;
CREATE POLICY "Public read kb files"
    ON storage.objects FOR SELECT TO anon, authenticated
    USING (bucket_id = 'kb-files');

DROP POLICY IF EXISTS "Allow kb files upload" ON storage.objects;
CREATE POLICY "Allow kb files upload"
    ON storage.objects FOR INSERT TO anon, authenticated
    WITH CHECK (bucket_id = 'kb-files');


-- ---------------------------------------------------------------------------
-- Legacy cleanup
-- ---------------------------------------------------------------------------

DROP TABLE IF EXISTS demo_links CASCADE;
DROP TABLE IF EXISTS message_assets CASCADE;
DROP TABLE IF EXISTS automation_jobs CASCADE;
DROP TABLE IF EXISTS wa_events CASCADE;
DROP TABLE IF EXISTS wa_messages CASCADE;
DROP TABLE IF EXISTS wa_templates CASCADE;
DROP TABLE IF EXISTS wa_conversations CASCADE;
DROP TABLE IF EXISTS kb_structured_entities CASCADE;
