"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 00:45:47.732906
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('calls_today', sa.Integer(), nullable=False),
    sa.Column('calls_total', sa.Integer(), nullable=False),
    sa.Column('avg_duration', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_active', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_csv', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('scheduled_start', sa.String(length=100), nullable=False),
    sa.Column('scheduled_end', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('call_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('caller_name', sa.String(length=100), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('was_booked', sa.Boolean(), nullable=False),
    sa.Column('interrupt_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('call_date', sa.String(length=50), nullable=True),
    sa.Column('call_hour', sa.Integer(), nullable=True),
    sa.Column('call_day_of_week', sa.String(length=50), nullable=True),
    sa.Column('call_room_id', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_call_room_id'), ['call_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('call_turn_metrics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('call_room_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=False),
    sa.Column('stt_endpoint_ms', sa.Float(), nullable=True),
    sa.Column('kb_ms', sa.Float(), nullable=True),
    sa.Column('llm_first_token_ms', sa.Float(), nullable=True),
    sa.Column('tts_first_audio_ms', sa.Float(), nullable=True),
    sa.Column('tool_ms', sa.Float(), nullable=True),
    sa.Column('total_turn_ms', sa.Float(), nullable=True),
    sa.Column('kb_used', sa.Boolean(), nullable=False),
    sa.Column('kb_skipped_reason', sa.String(length=250), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_turn_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_turn_metrics_call_room_id'), ['call_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_turn_metrics_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('retry_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cms_faqs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_faqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_faqs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cms_media',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_media_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cms_pages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_pages_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_cms_pages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cms_prompts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tags_csv', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_prompts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.String(length=50), nullable=False),
    sa.Column('score_explanation', sa.Text(), nullable=True),
    sa.Column('assigned_agent', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('neet_score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('parent_involved', sa.Boolean(), nullable=False),
    sa.Column('country_preference', sa.String(length=150), nullable=True),
    sa.Column('follow_up_date', sa.String(length=50), nullable=True),
    sa.Column('objection', sa.Text(), nullable=True),
    sa.Column('session_booked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_subdomain'), ['subdomain'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('success', sa.Float(), nullable=False),
    sa.Column('joined', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('trigger_event', sa.String(length=150), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('campaign_leads',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('lead_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('call_room_id', sa.String(length=100), nullable=True),
    sa.Column('custom_fields_json', sa.Text(), nullable=True),
    sa.Column('last_dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_leads_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_leads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lead_activities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('lead_id', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_activities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_activities_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workflow_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_id', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_logs_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_logs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_logs_tenant_id'))

    op.drop_table('workflow_logs')
    with op.batch_alter_table('lead_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_activities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lead_activities_lead_id'))

    op.drop_table('lead_activities')
    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_leads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_leads_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_leads_campaign_id'))

    op.drop_table('campaign_leads')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_tenant_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_subdomain'))

    op.drop_table('tenants')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_tenant_id'))

    op.drop_table('leads')
    with op.batch_alter_table('cms_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_prompts_tenant_id'))

    op.drop_table('cms_prompts')
    with op.batch_alter_table('cms_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_pages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cms_pages_slug'))

    op.drop_table('cms_pages')
    with op.batch_alter_table('cms_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_media_tenant_id'))

    op.drop_table('cms_media')
    with op.batch_alter_table('cms_faqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_faqs_tenant_id'))

    op.drop_table('cms_faqs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_tenant_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('call_turn_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_turn_metrics_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_call_turn_metrics_call_room_id'))

    op.drop_table('call_turn_metrics')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_call_room_id'))

    op.drop_table('call_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_tenant_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
