"""tenant not null fk

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 01:01:44.852113
"""
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


# Child tables inherit the tenant of their parent row.
_PARENT_LINKS = (
    ("lead_activities", "lead_id", "leads"),
    ("campaign_leads", "campaign_id", "campaigns"),
    ("workflow_logs", "workflow_id", "workflows"),
    ("auth_sessions", "user_id", "users"),
)
_TENANT_TABLES = (
    "agents", "appointments", "auth_sessions", "call_logs", "call_turn_metrics", "campaign_leads", "campaigns",
    "cms_faqs", "cms_media", "cms_pages", "cms_prompts", "invitations", "lead_activities", "leads", "users",
    "workflow_logs", "workflows",
)
_MISSING = "(tenant_id IS NULL OR tenant_id NOT IN (SELECT id FROM tenants))"


def _repair_tenant_ids() -> None:
    """Give every row a real tenant before the column becomes a required foreign key. Never deletes data."""
    conn = op.get_bind()
    for child, fk, parent in _PARENT_LINKS:
        conn.execute(sa.text(
            f"UPDATE {child} SET tenant_id = (SELECT p.tenant_id FROM {parent} p WHERE p.id = {child}.{fk}) "
            f"WHERE {_MISSING} AND EXISTS (SELECT 1 FROM {parent} p WHERE p.id = {child}.{fk} "
            f"AND p.tenant_id IN (SELECT id FROM tenants))"
        ))

    remaining = sum(conn.execute(sa.text(f"SELECT COUNT(*) FROM {t} WHERE {_MISSING}")).scalar() for t in _TENANT_TABLES)
    conn.execute(sa.text("UPDATE audit_logs SET tenant_id = NULL WHERE tenant_id NOT IN (SELECT id FROM tenants)"))
    if remaining == 0:
        return

    tenant_ids = [row[0] for row in conn.execute(sa.text("SELECT id FROM tenants")).fetchall()]
    if len(tenant_ids) == 1:
        target = tenant_ids[0]
    else:
        target = str(uuid.uuid4())
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        conn.execute(
            sa.text("INSERT INTO tenants (id, name, plan, status, created_at, updated_at) "
                    "VALUES (:id, 'Unassigned data (migrated)', 'Free', 'active', :now, :now)"),
            {"id": target, "now": now},
        )
    for table in _TENANT_TABLES:
        conn.execute(sa.text(f"UPDATE {table} SET tenant_id = :t WHERE {_MISSING}"), {"t": target})


def upgrade() -> None:
    _repair_tenant_ids()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_agents_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_appointments_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_auth_sessions_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')


    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_call_logs_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('call_turn_metrics', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_call_turn_metrics_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_campaign_leads_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_campaigns_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cms_faqs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_cms_faqs_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cms_media', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_cms_media_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cms_pages', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_cms_pages_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cms_prompts', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_cms_prompts_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_invitations_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lead_activities', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_lead_activities_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_leads_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflow_logs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_workflow_logs_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_workflows_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workflows_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('workflow_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workflow_logs_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leads_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('lead_activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lead_activities_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invitations_tenant_id_tenants'), type_='foreignkey')

    with op.batch_alter_table('cms_prompts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cms_prompts_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('cms_pages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cms_pages_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('cms_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cms_media_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('cms_faqs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cms_faqs_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_campaigns_tenant_id_tenants'), type_='foreignkey')

    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_campaign_leads_tenant_id_tenants'), type_='foreignkey')

    with op.batch_alter_table('call_turn_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_call_turn_metrics_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_call_logs_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)


    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auth_sessions_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_tenant_id_tenants'), type_='foreignkey')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agents_tenant_id_tenants'), type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
