"""agent versions

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25 01:21:00.670900
"""
import json
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


_NEW_TENANT_TABLES = ("agent_versions", "agent_changes", "agent_lifecycle_events")
_TENANT_MATCH = (
    "(NULLIF(current_setting('app.tenant_id', true), '') IS NULL "
    "OR tenant_id = current_setting('app.tenant_id', true))"
)


def _default_config(voice: str | None, model: str | None) -> dict:
    return {
        "schema_version": 1, "instructions": "", "greetings": {},
        "languages": {"supported": ["en"], "default": "en", "auto_detect": True},
        "llm": {"model": "gemini-2.5-flash", "temperature": 0.7},
        "voice": {"voice": voice or "Puck", "live_model": model or "gemini-2.0-flash-live-001"},
        "limits": {"max_call_seconds": 300},
        "hours": {"timezone": "Asia/Kolkata", "days": ["Mon", "Tue", "Wed", "Thu", "Fri"], "start": "09:00", "end": "18:00"},
        "handoff": {"phone": ""}, "knowledge": {"source_ids": []}, "tools": [], "workflow_id": None,
    }


def _move_voice_and_model_into_versions() -> None:
    """Each existing agent keeps behaving the same: its settings become version 1, in production."""
    conn = op.get_bind()
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    agents = conn.execute(sa.text("SELECT id, tenant_id, voice, model FROM agents")).fetchall()
    for agent_id, tenant_id, voice, model in agents:
        version_id = str(uuid.uuid4())
        conn.execute(sa.text(
            "INSERT INTO agent_versions (id, tenant_id, agent_id, number, status, config, created_at, updated_at, activated_at) "
            "VALUES (:id, :tenant, :agent, 1, 'production', :config, :now, :now, :now)"
        ), {"id": version_id, "tenant": tenant_id, "agent": agent_id,
            "config": json.dumps(_default_config(voice, model)), "now": now})
        conn.execute(sa.text("UPDATE agents SET production_version_id = :v WHERE id = :a"), {"v": version_id, "a": agent_id})
        conn.execute(sa.text(
            "INSERT INTO agent_lifecycle_events (id, tenant_id, agent_id, version_id, action, from_status, to_status, note, created_at) "
            "VALUES (:id, :tenant, :agent, :version, 'migrate', NULL, 'production', 'Imported from pre-versioning agent', :now)"
        ), {"id": str(uuid.uuid4()), "tenant": tenant_id, "agent": agent_id, "version": version_id, "now": now})


def _enable_rls() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in _NEW_TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation ON {table} USING {_TENANT_MATCH} WITH CHECK {_TENANT_MATCH}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('based_on_version_id', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_versions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_agent_versions_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_versions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent_id', 'number', name=op.f('uq_agent_versions_agent_id'))
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_changes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('version_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_changes_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_changes_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_changes_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], name=op.f('fk_agent_changes_version_id_agent_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_changes'))
    )
    with op.batch_alter_table('agent_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_changes_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_changes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_changes_version_id'), ['version_id'], unique=False)

    op.create_table('agent_lifecycle_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('version_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_lifecycle_events_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_lifecycle_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_lifecycle_events_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], name=op.f('fk_agent_lifecycle_events_version_id_agent_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_lifecycle_events'))
    )
    with op.batch_alter_table('agent_lifecycle_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_lifecycle_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_lifecycle_events_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_version_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('draft_version_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('disabled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_agents_production_version_id_agent_versions'), 'agent_versions', ['production_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_agents_draft_version_id_agent_versions'), 'agent_versions', ['draft_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_agents_created_by_users'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    _move_voice_and_model_into_versions()
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('voice')
        batch_op.drop_column('model')
    _enable_rls()


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for table in _NEW_TENANT_TABLES:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('voice', sa.VARCHAR(length=100), nullable=True))
    conn = op.get_bind()
    for agent_id, config in conn.execute(sa.text(
            "SELECT a.id, v.config FROM agents a JOIN agent_versions v ON v.id = COALESCE(a.production_version_id, a.draft_version_id)")).fetchall():
        cfg = json.loads(config) if isinstance(config, str) else config
        conn.execute(sa.text("UPDATE agents SET voice = :v, model = :m WHERE id = :a"),
                     {"v": cfg["voice"]["voice"], "m": cfg["voice"]["live_model"], "a": agent_id})
    conn.execute(sa.text("UPDATE agents SET voice = COALESCE(voice, 'Puck'), model = COALESCE(model, 'gemini-2.0-flash-live-001')"))
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agents_created_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_agents_draft_version_id_agent_versions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_agents_production_version_id_agent_versions'), type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('disabled_at')
        batch_op.drop_column('draft_version_id')
        batch_op.drop_column('production_version_id')

    with op.batch_alter_table('agent_lifecycle_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_lifecycle_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_lifecycle_events_agent_id'))

    op.drop_table('agent_lifecycle_events')
    with op.batch_alter_table('agent_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_changes_version_id'))
        batch_op.drop_index(batch_op.f('ix_agent_changes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_changes_agent_id'))

    op.drop_table('agent_changes')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))

    op.drop_table('agent_versions')
    # ### end Alembic commands ###
