"""knowledge base tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 10:50:20.076987
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


EMBEDDING_DIMENSIONS = 768
_TABLES = ("kb_sources", "kb_documents", "kb_chunks", "kb_ingest_jobs")
_TENANT_MATCH = (
    "(NULLIF(current_setting('app.tenant_id', true), '') IS NULL "
    "OR tenant_id = current_setting('app.tenant_id', true))"
)


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _embedding_type():
    if _is_postgres():
        from pgvector.sqlalchemy import Vector
        return Vector(EMBEDDING_DIMENSIONS)
    return sa.JSON()


def _require_pgvector() -> None:
    conn = op.get_bind()
    if conn.execute(sa.text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")).scalar():
        return
    can_create = conn.execute(sa.text("SELECT rolsuper FROM pg_roles WHERE rolname = current_user")).scalar()
    if not can_create:
        raise RuntimeError(
            "The pgvector extension is not enabled in this database. Ask a database admin to run "
            "`CREATE EXTENSION vector;` once (or enable 'vector' in your provider's extensions page), then restart."
        )
    conn.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))


def _postgres_indexes_and_rls() -> None:
    op.execute("CREATE INDEX ix_kb_chunks_embedding_hnsw ON kb_chunks USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX ix_kb_chunks_search_tokens_fts ON kb_chunks USING gin (to_tsvector('simple', search_tokens))")
    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation ON {table} USING {_TENANT_MATCH} WITH CHECK {_TENANT_MATCH}")


def upgrade() -> None:
    if _is_postgres():
        _require_pgvector()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('storage_bucket', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kb_sources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_sources'))
    )
    with op.batch_alter_table('kb_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_sources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kb_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], name=op.f('fk_kb_documents_source_id_kb_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kb_documents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_documents')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_kb_documents_source_id'))
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kb_ingest_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], name=op.f('fk_kb_ingest_jobs_source_id_kb_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kb_ingest_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_ingest_jobs'))
    )
    with op.batch_alter_table('kb_ingest_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_ingest_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_ingest_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_ingest_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kb_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_tokens', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('embedding', _embedding_type(), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_documents.id'], name=op.f('fk_kb_chunks_document_id_kb_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], name=op.f('fk_kb_chunks_source_id_kb_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kb_chunks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name=op.f('uq_kb_chunks_document_id'))
    )
    with op.batch_alter_table('kb_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_chunks_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_chunks_tenant_id'), ['tenant_id'], unique=False)

    if _is_postgres():
        _postgres_indexes_and_rls()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_chunks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_kb_chunks_source_id'))
        batch_op.drop_index(batch_op.f('ix_kb_chunks_document_id'))

    op.drop_table('kb_chunks')
    with op.batch_alter_table('kb_ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_ingest_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_kb_ingest_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_kb_ingest_jobs_source_id'))

    op.drop_table('kb_ingest_jobs')
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_kb_documents_source_id'))

    op.drop_table('kb_documents')
    with op.batch_alter_table('kb_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_sources_tenant_id'))

    op.drop_table('kb_sources')
    # ### end Alembic commands ###
