"""cms slug unique per tenant

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-25 11:49:16.961904
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_pages', schema=None) as batch_op:
        batch_op.drop_index('ix_cms_pages_slug')
        batch_op.create_index(batch_op.f('ix_cms_pages_slug'), ['slug'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_cms_pages_tenant_id'), ['tenant_id', 'slug'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_pages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cms_pages_tenant_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_cms_pages_slug'))
        batch_op.create_index('ix_cms_pages_slug', ['slug'], unique=1)

    # ### end Alembic commands ###
